"""Request/response schemas for images.

The upload request itself is multipart/form-data (handled by the route), so
there is no Pydantic body schema for it; what follows describes responses.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from app.models.image import ImageStatus


class ImageResponse(BaseModel):
    """Metadata for one image. `s3_url` may be null until a (presigned) URL
    is generated by the service from the stored s3_key."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    event_id: int
    s3_url: str | None = None
    original_filename: str
    status: ImageStatus
    created_at: datetime


class ImageUploadResponse(BaseModel):
    """Acknowledgement returned as soon as the images are stored in S3 and
    queued - processing happens in the background."""

    event_id: int
    accepted: int = Field(description="Number of images stored and queued.")
    image_ids: list[int]
